/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiExtractRecipeVideoRouteImport } from './routes/api/extract-recipe-video'
import { Route as ApiExtractRecipeUrlRouteImport } from './routes/api/extract-recipe-url'
import { Route as ApiExtractRecipeRouteImport } from './routes/api/extract-recipe'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedReceitaIdRouteImport } from './routes/_authenticated/receita.$id'
import { Route as AuthenticatedExplorarIdRouteImport } from './routes/_authenticated/explorar.$id'
import { Route as AuthenticatedReceitaIdCozinharRouteImport } from './routes/_authenticated/receita.$id.cozinhar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiExtractRecipeVideoRoute = ApiExtractRecipeVideoRouteImport.update({
  id: '/api/extract-recipe-video',
  path: '/api/extract-recipe-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRecipeUrlRoute = ApiExtractRecipeUrlRouteImport.update({
  id: '/api/extract-recipe-url',
  path: '/api/extract-recipe-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRecipeRoute = ApiExtractRecipeRouteImport.update({
  id: '/api/extract-recipe',
  path: '/api/extract-recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReceitaIdRoute = AuthenticatedReceitaIdRouteImport.update({
  id: '/receita/$id',
  path: '/receita/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExplorarIdRoute = AuthenticatedExplorarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedExplorarRoute,
} as any)
const AuthenticatedReceitaIdCozinharRoute =
  AuthenticatedReceitaIdCozinharRouteImport.update({
    id: '/cozinhar',
    path: '/cozinhar',
    getParentRoute: () => AuthenticatedReceitaIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/explorar': typeof AuthenticatedExplorarRouteWithChildren
  '/importar': typeof AuthenticatedImportarRoute
  '/api/extract-recipe': typeof ApiExtractRecipeRoute
  '/api/extract-recipe-url': typeof ApiExtractRecipeUrlRoute
  '/api/extract-recipe-video': typeof ApiExtractRecipeVideoRoute
  '/explorar/$id': typeof AuthenticatedExplorarIdRoute
  '/receita/$id': typeof AuthenticatedReceitaIdRouteWithChildren
  '/receita/$id/cozinhar': typeof AuthenticatedReceitaIdCozinharRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/explorar': typeof AuthenticatedExplorarRouteWithChildren
  '/importar': typeof AuthenticatedImportarRoute
  '/api/extract-recipe': typeof ApiExtractRecipeRoute
  '/api/extract-recipe-url': typeof ApiExtractRecipeUrlRoute
  '/api/extract-recipe-video': typeof ApiExtractRecipeVideoRoute
  '/': typeof AuthenticatedIndexRoute
  '/explorar/$id': typeof AuthenticatedExplorarIdRoute
  '/receita/$id': typeof AuthenticatedReceitaIdRouteWithChildren
  '/receita/$id/cozinhar': typeof AuthenticatedReceitaIdCozinharRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRouteWithChildren
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/api/extract-recipe': typeof ApiExtractRecipeRoute
  '/api/extract-recipe-url': typeof ApiExtractRecipeUrlRoute
  '/api/extract-recipe-video': typeof ApiExtractRecipeVideoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/explorar/$id': typeof AuthenticatedExplorarIdRoute
  '/_authenticated/receita/$id': typeof AuthenticatedReceitaIdRouteWithChildren
  '/_authenticated/receita/$id/cozinhar': typeof AuthenticatedReceitaIdCozinharRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compras'
    | '/explorar'
    | '/importar'
    | '/api/extract-recipe'
    | '/api/extract-recipe-url'
    | '/api/extract-recipe-video'
    | '/explorar/$id'
    | '/receita/$id'
    | '/receita/$id/cozinhar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/compras'
    | '/explorar'
    | '/importar'
    | '/api/extract-recipe'
    | '/api/extract-recipe-url'
    | '/api/extract-recipe-video'
    | '/'
    | '/explorar/$id'
    | '/receita/$id'
    | '/receita/$id/cozinhar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/compras'
    | '/_authenticated/explorar'
    | '/_authenticated/importar'
    | '/api/extract-recipe'
    | '/api/extract-recipe-url'
    | '/api/extract-recipe-video'
    | '/_authenticated/'
    | '/_authenticated/explorar/$id'
    | '/_authenticated/receita/$id'
    | '/_authenticated/receita/$id/cozinhar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiExtractRecipeRoute: typeof ApiExtractRecipeRoute
  ApiExtractRecipeUrlRoute: typeof ApiExtractRecipeUrlRoute
  ApiExtractRecipeVideoRoute: typeof ApiExtractRecipeVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/extract-recipe-video': {
      id: '/api/extract-recipe-video'
      path: '/api/extract-recipe-video'
      fullPath: '/api/extract-recipe-video'
      preLoaderRoute: typeof ApiExtractRecipeVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-recipe-url': {
      id: '/api/extract-recipe-url'
      path: '/api/extract-recipe-url'
      fullPath: '/api/extract-recipe-url'
      preLoaderRoute: typeof ApiExtractRecipeUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract-recipe': {
      id: '/api/extract-recipe'
      path: '/api/extract-recipe'
      fullPath: '/api/extract-recipe'
      preLoaderRoute: typeof ApiExtractRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receita/$id': {
      id: '/_authenticated/receita/$id'
      path: '/receita/$id'
      fullPath: '/receita/$id'
      preLoaderRoute: typeof AuthenticatedReceitaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/explorar/$id': {
      id: '/_authenticated/explorar/$id'
      path: '/$id'
      fullPath: '/explorar/$id'
      preLoaderRoute: typeof AuthenticatedExplorarIdRouteImport
      parentRoute: typeof AuthenticatedExplorarRoute
    }
    '/_authenticated/receita/$id/cozinhar': {
      id: '/_authenticated/receita/$id/cozinhar'
      path: '/cozinhar'
      fullPath: '/receita/$id/cozinhar'
      preLoaderRoute: typeof AuthenticatedReceitaIdCozinharRouteImport
      parentRoute: typeof AuthenticatedReceitaIdRoute
    }
  }
}

interface AuthenticatedExplorarRouteChildren {
  AuthenticatedExplorarIdRoute: typeof AuthenticatedExplorarIdRoute
}

const AuthenticatedExplorarRouteChildren: AuthenticatedExplorarRouteChildren = {
  AuthenticatedExplorarIdRoute: AuthenticatedExplorarIdRoute,
}

const AuthenticatedExplorarRouteWithChildren =
  AuthenticatedExplorarRoute._addFileChildren(
    AuthenticatedExplorarRouteChildren,
  )

interface AuthenticatedReceitaIdRouteChildren {
  AuthenticatedReceitaIdCozinharRoute: typeof AuthenticatedReceitaIdCozinharRoute
}

const AuthenticatedReceitaIdRouteChildren: AuthenticatedReceitaIdRouteChildren =
  {
    AuthenticatedReceitaIdCozinharRoute: AuthenticatedReceitaIdCozinharRoute,
  }

const AuthenticatedReceitaIdRouteWithChildren =
  AuthenticatedReceitaIdRoute._addFileChildren(
    AuthenticatedReceitaIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRouteWithChildren
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedReceitaIdRoute: typeof AuthenticatedReceitaIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRouteWithChildren,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedReceitaIdRoute: AuthenticatedReceitaIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiExtractRecipeRoute: ApiExtractRecipeRoute,
  ApiExtractRecipeUrlRoute: ApiExtractRecipeUrlRoute,
  ApiExtractRecipeVideoRoute: ApiExtractRecipeVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
